revert concurrent-ruby from 1.3.5 to 1.3.4
After merging several dependabot PRs, the program would not start:

```
rake aborted!
NameError: uninitialized constant ActiveSupport::LoggerThreadSafeLevel::Logger (NameError)

    Logger::Severity.constants.each do |severity|
          ^^^^^^^^^^
```
The real fix seems to be upgrading to Rails 7.1. For now, I followed the recommendation in this [StackOverflow post](https://stackoverflow.com/questions/79360526/uninitialized-constant-activesupportloggerthreadsafelevellogger-nameerror).