first attempt at upgrading to 4.4.2
- followed the 4.4 upgrade notes in [Release v.4.4.0.rc1](https://github.com/geoblacklight/geoblacklight/releases/tag/v4.4.0.rc1)
- encountered many errors
- upgraded ruby to 3.2.7 (latest in 3.2)
- upgraded rails to 7.2.x

GBL will now successfully launch and display the home page, and will successfully display the search page.

However, displaying a record with a IIIF link produces this error:

```
Showing /Users/rseifried/github/umass-gis/geoblacklight/app/views/layouts/blacklight/base.html.erb where line #24 raised:

Vite Ruby can't find entrypoints/clover.js in the manifests.

Possible causes:
  - The last build failed. Try running `bin/vite build --clear --mode=development` manually and check for errors.

Errors:
  x Build failed in 21ms
  error during build:
  [vite:css] Failed to load PostCSS config (searchPath: /Users/rseifried/github/umass-gis/geoblacklight/app/javascript): [Error] Cannot find module 'postcss-import'
  Require stack:
  - /Users/rseifried/github/umass-gis/geoblacklight/postcss.config.js
  Error: Cannot find module 'postcss-import'
  Require stack:
  - /Users/rseifried/github/umass-gis/geoblacklight/postcss.config.js
      at Function._resolveFilename (node:internal/modules/cjs/loader:1394:15)
      at defaultResolveImpl (node:internal/modules/cjs/loader:1050:19)
      at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1055:22)
      at Function._load (node:internal/modules/cjs/loader:1204:37)
      at TracingChannel.traceSync (node:diagnostics_channel:322:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:234:24)
      at Module.require (node:internal/modules/cjs/loader:1480:12)
      at require (node:internal/modules/helpers:135:16)
      at Object.<anonymous> (/Users/rseifried/github/umass-gis/geoblacklight/postcss.config.js:3:5)
      at Module._compile (node:internal/modules/cjs/loader:1723:14)
  file: /Users/rseifried/github/umass-gis/geoblacklight/node_modules/@geoblacklight/frontend/dist/style.css

Visit the Troubleshooting guide for more information:
  https://vite-ruby.netlify.app/guide/troubleshooting.html#troubleshooting
```